language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "devmeex-github" 
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

jdk:
    - oraclejdk8

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - sonar-scanner
    
deploy:
  provider: heroku
  api_key: 1eea512a-0902-4ffc-9f82-87083eab5807
  app: ci-hellomundo
