language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "devmeex-github" # the key of the org you chose at step #3
    token:
      secure: "42c82f85a130f2abf1b803287c29e8e5924960bb" # encrypted value of your token

jdk:
    - openjdk11

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'    
deploy:
  provider: heroku
  api_key: 1eea512a-0902-4ffc-9f82-87083eab5807
  app: ci-hellomundo
