language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "devmeex-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

jdk:
    - oraclejdk8

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - mvn verify clean sonar:sonar
    - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar

    
deploy:
  provider: heroku
  api_key: 1eea512a-0902-4ffc-9f82-87083eab5807
  app: ci-hellomundo
